#!/usr/bin/env python3
"""
End-to-end integration test: AIR MFMA single tile -> Aster -> AMDGCN assembly.

This script demonstrates the full AIR-to-Aster pipeline:
  1. Reads the AIR-dialect MFMA test input
  2. Runs air-opt -air-to-aster to annotate with GPU target metadata
  3. Generates equivalent Aster-format MLIR (matching test_002_mfma.mlir)
  4. Runs aster-opt with the full FUTURE_SROA pass pipeline
  5. Runs aster-translate --mlir-to-asm to produce gfx942 assembly
  6. Verifies the assembly contains v_mfma_f32_16x16x16_f16

Usage:
  python3 run_e2e.py [--air-opt PATH] [--aster-opt PATH] [--aster-translate PATH]
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MLIR_AIR_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "..", ".."))
ASTER_ROOT = os.path.join(MLIR_AIR_ROOT, "aster")

# AIR input files
AIR_INPUT_DMA = os.path.join(
    MLIR_AIR_ROOT,
    "mlir", "test", "Conversion", "AIRToAster",
    "air_mfma_single_tile.mlir",
)
AIR_INPUT_CHANNEL = os.path.join(
    MLIR_AIR_ROOT,
    "mlir", "test", "Conversion", "AIRToAster",
    "air_channel_mfma.mlir",
)
AIR_INPUT_SYNC = os.path.join(
    MLIR_AIR_ROOT,
    "mlir", "test", "Conversion", "AIRToAster",
    "air_channel_mfma_sync.mlir",
)
AIR_INPUT_DMA_SYNC = os.path.join(
    MLIR_AIR_ROOT,
    "mlir", "test", "Conversion", "AIRToAster",
    "air_dma_mfma_sync.mlir",
)
# Default: use DMA-based sync input (most realistic / earliest pipeline stage)
AIR_INPUT = AIR_INPUT_DMA_SYNC

# Aster library paths needed for test_002_mfma
KITTENS_LIB = os.path.join(ASTER_ROOT, "contrib", "kittens", "library")
COMMON_LIB = os.path.join(ASTER_ROOT, "mlir_kernels", "library", "common")
LIBRARY_PATHS = ",".join([
    os.path.join(COMMON_LIB, "register-init.mlir"),
    os.path.join(COMMON_LIB, "futures.mlir"),
    os.path.join(COMMON_LIB, "indexing.mlir"),
    os.path.join(COMMON_LIB, "simple-copies.mlir"),
    os.path.join(KITTENS_LIB, "global_16x16_f16.mlir"),
])

# Aster pass pipeline (FUTURE_SROA from pass_pipelines.py)
ASTER_PIPELINE = (
    "builtin.module("
    "aster-selective-inlining,cse,canonicalize,symbol-dce,"
    "amdgcn-instruction-scheduling-autoschedule,aster-op-scheduling,"
    "aster-selective-inlining{allow-scheduled-calls=true},"
    "aster-replace-constant-gpu-dims,cse,canonicalize,"
    "cse,canonicalize,sroa,cse,canonicalize,amdgcn-mem2reg,"
    "aster-selective-inlining{allow-scheduled-calls=true},"
    "cse,canonicalize,symbol-dce,aster-constexpr-expansion,"
    "cse,canonicalize,affine-expand-index-ops-as-affine,"
    "cse,canonicalize,sroa,cse,canonicalize,amdgcn-mem2reg,"
    "aster-selective-inlining{allow-scheduled-calls=true},"
    "cse,canonicalize,symbol-dce,aster-constexpr-expansion,"
    "cse,canonicalize,amdgcn-lds-alloc,amdgcn-convert-lds-buffers,"
    "canonicalize,cse,"
    "amdgcn.module(amdgcn.kernel(aster-amdgcn-expand-md-ops,canonicalize,cse)),"
    "aster-to-int-arith,aster-optimize-arith,canonicalize,cse,"
    "aster-resolve-any-iter-args,aster-amdgcn-set-abi,"
    "amdgcn-convert-scf-control-flow,canonicalize,cse,"
    "aster-codegen,canonicalize,cse,canonicalize,aster-to-amdgcn,"
    "amdgcn-backend,amdgcn-remove-test-inst,"
    "amdgcn-nop-insertion{conservative-extra-delays=0})"
)


def extract_aster_mlir(annotated_ir: str) -> str:
    """Extract the Aster MLIR generated by the C++ air-to-aster pass.

    The pass walks the AIR IR structurally (channels, async tokens, compute
    patterns) and emits Aster-format MLIR text, stored as the
    'aster.generated_mlir' module attribute. This function extracts it.

    No templates. No hardcoding. The Aster MLIR is derived from the actual
    AIR IR by the C++ pass analyzing:
      - air.channel.get/put ops -> load/store library calls
      - air.execute { linalg.generic matmul } -> mfma call
      - memref shapes/types -> strides, element sizes
      - func.func args -> kernel buffer arguments
    """
    # The C++ pass stores the generated MLIR in the aster.generated_mlir
    # attribute on the module op. Extract it from the printed IR.
    marker = 'aster.generated_mlir = "'
    start = annotated_ir.find(marker)
    if start < 0:
        raise RuntimeError(
            "aster.generated_mlir attribute not found in air-opt output. "
            "Ensure air-to-aster pass ran successfully."
        )
    start += len(marker)
    # Find the closing quote, handling escaped characters
    end = start
    while end < len(annotated_ir):
        if annotated_ir[end] == '"' and annotated_ir[end - 1] != '\\':
            break
        end += 1
    raw = annotated_ir[start:end]
    # MLIR string attributes use \0A for newline (hex escape), \22 for quote
    result = raw.replace("\\0A", "\n").replace("\\22", '"').replace("\\\\", "\\")
    return result


def run_cmd(cmd, input_data=None, desc=""):
    """Run a command, returning stdout. Raises on failure."""
    result = subprocess.run(
        cmd, input=input_data, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"FAIL: {desc}", file=sys.stderr)
        print(f"  Command: {' '.join(cmd)}", file=sys.stderr)
        print(f"  Stderr: {result.stderr[:1000]}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def main():
    parser = argparse.ArgumentParser(description="AIR -> Aster MFMA e2e test")
    parser.add_argument("--air-opt", default=os.path.join(MLIR_AIR_ROOT, "build", "bin", "air-opt"))
    parser.add_argument("--aster-opt", default=os.path.join(ASTER_ROOT, "build", "bin", "aster-opt"))
    parser.add_argument("--aster-translate", default=os.path.join(ASTER_ROOT, "build", "bin", "aster-translate"))
    parser.add_argument("--dump-intermediate", action="store_true", help="Dump intermediate MLIR files")
    parser.add_argument("--input",
                        choices=["dma-sync", "sync", "channel", "dma"],
                        default="dma-sync",
                        help="AIR input variant: "
                             "'dma-sync' (DMAs, no channels/tokens, default), "
                             "'sync' (channels, no tokens), "
                             "'channel' (channels with tokens), "
                             "'dma' (DMAs with tokens)")
    args = parser.parse_args()

    # Select input file and AIR pass pipeline
    aster_flag = '-air-to-aster=device=gfx942 wave-size=64'
    air_passes = [aster_flag]
    if args.input == "dma-sync":
        air_input = AIR_INPUT_DMA_SYNC
        air_passes = ["-air-dependency", "-air-dependency-canonicalize",
                      "-air-dma-to-channel", "-canonicalize", "-cse",
                      aster_flag]
    elif args.input == "sync":
        air_input = AIR_INPUT_SYNC
        air_passes = ["-air-dependency", "-air-dependency-canonicalize", aster_flag]
    elif args.input == "dma":
        air_input = AIR_INPUT_DMA
    else:
        air_input = AIR_INPUT_CHANNEL

    print("=" * 60)
    print("AIR -> Aster MFMA E2E Integration Test")
    print("=" * 60)

    # Step 1: Run air-opt -air-to-aster on AIR input
    print("\n[Step 1] Running air-opt -air-to-aster on AIR input...")
    air_cmd = [args.air_opt, air_input] + air_passes
    annotated_ir = run_cmd(
        air_cmd,
        desc="air-opt " + " ".join(air_passes),
    )
    print(f"  OK: AIR input annotated ({len(annotated_ir)} chars)")

    # Extract annotations
    annotations = {}
    for line in annotated_ir.split("\n"):
        if 'aster.target' in line:
            annotations["target"] = "gfx942"
        if 'aster.isa' in line:
            annotations["isa"] = "cdna3"
        if 'aster.block_dims' in line:
            annotations["block_dims"] = [64, 1, 1]
        if 'aster.wave_grid' in line:
            annotations["wave_grid"] = [1, 1]
    print(f"  Annotations: {annotations}")

    if args.dump_intermediate:
        with open("/tmp/air_annotated.mlir", "w") as f:
            f.write(annotated_ir)
        print("  Dumped: /tmp/air_annotated.mlir")

    # Step 2: Extract Aster MLIR generated by the C++ pass (from IR analysis)
    print("\n[Step 2] Extracting Aster MLIR from C++ pass output...")
    aster_mlir = extract_aster_mlir(annotated_ir)
    print(f"  OK: Generated Aster MLIR ({len(aster_mlir)} chars)")

    if args.dump_intermediate:
        with open("/tmp/aster_generated.mlir", "w") as f:
            f.write(aster_mlir)
        print("  Dumped: /tmp/aster_generated.mlir")

    # Step 3: Run aster-opt with library preloading + inlining
    print("\n[Step 3] Running aster-opt: library preload + inline...")
    inlined_ir = run_cmd(
        [args.aster_opt, "-",
         f"--amdgcn-preload-library=library-paths={LIBRARY_PATHS}",
         "--inline"],
        input_data=aster_mlir,
        desc="aster-opt preload+inline",
    )
    print(f"  OK: Libraries inlined ({len(inlined_ir)} chars)")

    if args.dump_intermediate:
        with open("/tmp/aster_inlined.mlir", "w") as f:
            f.write(inlined_ir)
        print("  Dumped: /tmp/aster_inlined.mlir")

    # Step 4: Run aster-opt with full pass pipeline
    print("\n[Step 4] Running aster-opt: full FUTURE_SROA pipeline...")
    lowered_ir = run_cmd(
        [args.aster_opt, "-", f"--pass-pipeline={ASTER_PIPELINE}"],
        input_data=inlined_ir,
        desc="aster-opt pass pipeline",
    )
    print(f"  OK: Lowered to AMDGCN IR ({len(lowered_ir)} chars)")

    if args.dump_intermediate:
        with open("/tmp/aster_lowered.mlir", "w") as f:
            f.write(lowered_ir)
        print("  Dumped: /tmp/aster_lowered.mlir")

    # Step 5: Translate to assembly
    print("\n[Step 5] Running aster-translate --mlir-to-asm...")
    assembly = run_cmd(
        [args.aster_translate, "-", "--mlir-to-asm"],
        input_data=lowered_ir,
        desc="aster-translate",
    )
    print(f"  OK: Assembly generated ({len(assembly)} chars)")

    if args.dump_intermediate:
        with open("/tmp/aster_output.s", "w") as f:
            f.write(assembly)
        print("  Dumped: /tmp/aster_output.s")

    # Step 6: Verify assembly
    print("\n[Step 6] Verifying assembly...")

    checks = {
        "MFMA instruction":        "v_mfma_f32_16x16x16_f16",
        "gfx942 target":           "gfx942",
        "global load":             "global_load_dwordx2",
        "global store":            "global_store_dword",
        "wait for memory":         "s_waitcnt",
        "kernel end":              "s_endpgm",
        "kernel symbol":           "forward:",
        "wavefront_size = 64":     "wavefront_size: 64",
    }

    all_pass = True
    for name, pattern in checks.items():
        if pattern in assembly:
            print(f"  PASS: {name} ({pattern})")
        else:
            print(f"  FAIL: {name} ({pattern}) NOT FOUND")
            all_pass = False

    # Print key assembly lines
    print("\n--- Key Assembly Lines ---")
    for line in assembly.split("\n"):
        stripped = line.strip()
        if any(k in stripped for k in [
            "v_mfma", "global_load", "global_store",
            "s_waitcnt", "s_endpgm", "forward:",
            ".amdgcn_target",
        ]):
            print(f"  {stripped}")

    print("\n" + "=" * 60)
    if all_pass:
        print("E2E TEST PASSED: AIR -> Aster -> AMDGCN assembly")
    else:
        print("E2E TEST FAILED: some checks did not pass")
        sys.exit(1)
    print("=" * 60)


if __name__ == "__main__":
    main()
